[package]
name = "openclassroom"
version = "0.1.0"
authors = ["TheTechRobo <52163910+TheTechRobo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

